import darklight from './dark-light'
import datetime from './date-time.js'
import geolocation from './geolocation.js'
import scripts from './scripts'
import share from './share'
import weather from './weather'